// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnswerChat'](arg1, arg2, arg3);
}

export function AreKeyExist() {
  return window['go']['main']['App']['AreKeyExist']();
}

export function ConfirmStartOver() {
  return window['go']['main']['App']['ConfirmStartOver']();
}

export function EndChat(arg1, arg2) {
  return window['go']['main']['App']['EndChat'](arg1, arg2);
}

export function StartChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartChat'](arg1, arg2, arg3);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function UpdateAPIKeys(arg1, arg2) {
  return window['go']['main']['App']['UpdateAPIKeys'](arg1, arg2);
}
